### ISSUE TITLE
_extract_xgz when preparing a backup

### ISSUE THREAD

**Issue by a-dawg** [dotmanila/pyxbackup#27] opened 2016-12-15 16:19 UTC
Hi
there is likely an issue when trying to prepare a compressed backup xbs.gz
```
pyxbackup --restore-backup=2016_12_13-15_52_35 --restore-dir=/home/backup/prepared-full restore-set
[12/15/2016 17:15:51] INFO: Found backup 2016_12_13-15_52_35 to prepare of type full
[12/15/2016 17:15:51] INFO: Decompressing /home/backup/full/2016_12_13-15_52_35/backup.xbs.gz
[12/15/2016 17:15:51] ERROR: An uncaught exception error has occurred!
Traceback (most recent call last):
  File "/usr/sbin/pyxbackup", line 3249, in <module>
    run_xb_restore_set()
  File "/usr/sbin/pyxbackup", line 2189, in run_xb_restore_set
    prepare_success = _prepare_backup(the_backup_path, prepare_path, finalize)
  File "/usr/sbin/pyxbackup", line 557, in _prepare_backup
    if not _decompress(bkp_file, cmp_to, meta):
  File "/usr/sbin/pyxbackup", line 1152, in _decompress
    return _extract_xgz(archive, dest, meta)
TypeError: _extract_xgz() takes exactly 2 arguments (3 given)
```

**Comment by a-dawg** [comment] 2016-12-20 12:16
such a patch would help. I don't know the advancement in meta information
```
-        return _extract_tgz(archive, dest, meta)
+        return _extract_tgz(archive, dest)
     elif archive[-6:] == 'xbs.gz':
-        return _extract_xgz(archive, dest, meta)
+        return _extract_xgz(archive, dest)
     elif archive[-6:]  == 'xbs.qp':
-        return _extract_stream_qpress(archive, dest, meta)
+        return _extract_stream_qpress(archive, dest)
     elif archive[-14:]  == 'xbs.qp.xbcrypt':
-        return _extract_stream_qpress(archive, dest, meta)
+        return _extract_stream_qpress(archive, dest)
     elif archive[-2:] == 'qp':
-        return _extract_nostream_qpress(archive, dest, meta)
+        return _extract_nostream_qpress(archive, dest)
     elif archive[-10:] == 'qp.xbcrypt':
-        return _extract_nostream_qpress(archive, dest, meta)
+        return _extract_nostream_qpress(archive, dest)

```

**Comment by Dinfangion** [comment] 2017-01-17 10:01
@a-dawg @dotmanila @grypyrg 
I ran into the above problem while preparing a restore.
_extract_xgz() takes exactly 2 arguments (3 given)

**Comment by b2cc** [comment] 2017-08-29 09:08
@dotmanila 
+1, we also ran into this issue and for now we also have to use the above mentioned fix from @a-dawg .

**Comment by hkheso** [comment] 2017-09-29 09:50
pyxbackup --version
pyxbackup 0.5
(installed 15.9.2017)
pyxbackup --config pyxbackup.cnf --restore-backup="2017_09_27-09_00_01" --restore-dir=... restore-set

confirmed: 
```
[09/29/2017 11:41:24] ERROR: An uncaught exception error has occurred!
Traceback (most recent call last):
  File "./pyxbackup", line 3406, in <module>
    run_xb_restore_set()
  File "./pyxbackup", line 2383, in run_xb_restore_set
    if not _prepare_backup(current_bkp, prepare_path):
  File "./pyxbackup", line 571, in _prepare_backup
    if not _decompress(bkp_file, cmp_to, meta):
  File "./pyxbackup", line 1164, in _decompress
    return _extract_tgz(archive, dest, meta)
TypeError: _extract_tgz() takes exactly 2 arguments (3 given)
```

This is three quarter of a year old and a fix was mentioned, is this repository EOL?

```
diff pyxbackup pyxbackup.orig 
1164c1164
<         return _extract_tgz(archive, dest)
---
>         return _extract_tgz(archive, dest, meta)
```

I only changed this, because I am not sure if the other option accepts "meta" parameter.
And it did work:
[09/29/2017 11:48:21] INFO: Prepare of backup 2017_09_27-09_00_01 successfully completed

But I am unsure about using this in production if such issues stay around for most of a year :-(

**Comment by nbokkisam** [comment] 2018-01-17 16:09
**This is still an issue. It's open for more than a year now.** anyone using this in production?

./pyxbackup --restore-backup=2018_01_17-10_39_48 --restore-dir=~/tmp/restore restore-set
[01/17/2018 10:59:09] FATAL: The specified prepare directory is not a valid directory
[root@test ~]# ./pyxbackup --restore-backup=2018_01_17-10_39_48 --restore-dir=/tmp/restore restore-set
[01/17/2018 10:59:24] INFO: Found backup 2018_01_17-10_39_48 to prepare of type incr
[01/17/2018 10:59:24] INFO: Decompressing /backups/folder/stor/full/2018_01_17-10_25_43/backup.tar.gz
[01/17/2018 10:59:24] ERROR: An uncaught exception error has occurred!
Traceback (most recent call last):
  File "./pyxbackup", line 3406, in <module>
    run_xb_restore_set()
  File "./pyxbackup", line 2383, in run_xb_restore_set
    if not _prepare_backup(current_bkp, prepare_path):
  File "./pyxbackup", line 571, in _prepare_backup
    if not _decompress(bkp_file, cmp_to, meta):
  File "./pyxbackup", line 1164, in _decompress
    return _extract_tgz(archive, dest, meta)
TypeError: _extract_tgz() takes exactly 2 arguments (3 given)

**Comment by Dinfangion** [comment] 2018-01-17 20:35
@nbokkisam 
I still use the previous version in production.
Not this one.

**Comment by nbokkisam** [comment] 2018-01-18 17:49
@Dinfangion 
what is the previous version? I don't see any tags in the master for versions. How do i get the previous version? Thanks.

**Comment by Dinfangion** [comment] 2018-01-19 19:58
@nbokkisam 
You can go the the pyxbackup file in this repo.
Then click on history.
We still have this one in production: https://github.com/dotmanila/pyxbackup/blob/3a9d9344e64365bb95a3aeddccab8dbbdc7d543c/pyxbackup 
It's an older version.

**Comment by nbokkisam** [comment] 2018-01-19 20:08
@Dinfangion Thank You.

**Comment by dotmanila** [comment] 2018-01-23 18:18
Thanks for your patience, this has been fixed on recent commits.

**Closed as completed by dotmanila** 2018-01-23 18:18 UTC
